### ISSUE TITLE
Tentative schedule

### ISSUE THREAD

**Issue by karthik** [datacarpentry/dc_eth#1]
### Tentative schedule for Swiss bootcamp

| Time | Topic |
| --- | --- |
| Tuesday 9-12 | Introduction, Spreadsheet basics, Introduction to R (with 30 minute coffee break) |
| Tuesday 1-5 | R (continued),  Manipulating data with dplyr, Introduction to data vizualization (with 30 minute coffee break) |
| Wednesday 9-12 | Introduction to the shell, SQL |
| Wednesday 1-5 | Interacting with APIs from R, Introduction to knitr/rmarkdown |
| Thursday | Off |
| Friday 9-12 | Introduction to version control with Git (Mattias) |
| Friday afternoon | Unscheduled, open to ad hoc topics (with 30 minute coffee break) |

Thoughts? @fmichonneau @pennekampster

**Comment by fmichonneau** [comment]
That looks good to me. Let me know your preference for which modules you'd like to teach, once @pennekampster agrees to the schedule.

**Comment by pennekampster** [comment]
### Updated schedule for Swiss bootcamp

| Time | Topic |
| --- | --- |
| Wednesday 9-12 | Introduction, Spreadsheet basics, Introduction to R (with 30 minute coffee break) |
| Wednesday 1-5 | R (continued),  Manipulating data with dplyr, Introduction to data vizualization (with 30 minute coffee break) |
| Thursday 9-12 | Introduction to the shell, SQL |
| Thursday 1-5 | Interacting with APIs from R, Introduction to knitr/rmarkdown |
| Friday 9-12 | Introduction to version control with Git (Mattias) |
| Friday afternoon | Unscheduled, open to ad hoc topics (with 30 minute coffee break) |
| Saturday 9-16 | Excursion |

Hi @fmichonneau @karthik,
updated schedule as written in email. Program looks fine but one suggestion based on R knowlegde of particpants: if some don't know R, let's do the regular DC curriculum, otherwise cover more of the Hadley-verse? Lubridate, reshape2, tidyr, readr etc? Or does that require too much prep?
